export const mapStates = [
  {
    id: "jk",
    name: "Jammu & Kashmir",
    x: 120,
    y: 42,
    width: 84,
    height: 44,
    rotate: -10,
    dishes: [
      {
        name: "Rogan Josh",
        description: "A deep, aromatic lamb curry built on Kashmiri chilies and warming spices.",
        recipeUrl: "/recipes",
      },
      {
        name: "Yakhni",
        description: "Silky yogurt-based gravy scented with fennel and dry mint.",
        recipeUrl: "/recipes",
      },
    ],
  },
  {
    id: "hp",
    name: "Himachal Pradesh",
    x: 200,
    y: 82,
    width: 60,
    height: 34,
    rotate: -6,
    dishes: [
      {
        name: "Dham",
        description: "A festive Himachali thali known for slow-cooked lentils and yogurt gravies.",
        recipeUrl: "/recipes",
      },
    ],
  },
  {
    id: "pb",
    name: "Punjab",
    x: 116,
    y: 106,
    width: 54,
    height: 44,
    rotate: -2,
    dishes: [
      {
        name: "Sarson da Saag",
        description: "Mustard greens cooked down into a velvety winter classic.",
        recipeUrl: "/recipes",
      },
      {
        name: "Makki di Roti",
        description: "Cornmeal flatbread that traditionally pairs with saag and white butter.",
        recipeUrl: "/recipes",
      },
    ],
  },
  {
    id: "uk",
    name: "Uttarakhand",
    x: 190,
    y: 122,
    width: 62,
    height: 34,
    rotate: -4,
    dishes: [
      {
        name: "Kafuli",
        description: "A mountain spinach gravy enriched with local greens and tempered spices.",
        recipeUrl: "/recipes",
      },
    ],
  },
  {
    id: "hr",
    name: "Haryana",
    x: 146,
    y: 154,
    width: 52,
    height: 42,
    rotate: 3,
    dishes: [
      {
        name: "Bajra Khichri",
        description: "Hearty pearl millet khichri built for earthy, comforting flavors.",
        recipeUrl: "/recipes",
      },
    ],
  },
  {
    id: "rj",
    name: "Rajasthan",
    x: 66,
    y: 184,
    width: 108,
    height: 94,
    rotate: -4,
    dishes: [
      {
        name: "Dal Baati Churma",
        description: "A royal trio of baked wheat dumplings, lentils, and sweet crumbly churma.",
        recipeUrl: "/recipes",
      },
      {
        name: "Gatte ki Sabzi",
        description: "Gram flour dumplings simmered in a tangy yogurt curry.",
        recipeUrl: "/recipes",
      },
    ],
  },
  {
    id: "up",
    name: "Uttar Pradesh",
    x: 186,
    y: 182,
    width: 118,
    height: 64,
    rotate: -2,
    dishes: [
      {
        name: "Galouti Kebab",
        description: "Lucknow's famously delicate kebab, rich with perfume-like spice notes.",
        recipeUrl: "/recipes",
      },
      {
        name: "Tehri",
        description: "A fragrant one-pot rice dish layered with vegetables and gentle spice.",
        recipeUrl: "/recipes",
      },
    ],
  },
  {
    id: "br",
    name: "Bihar",
    x: 308,
    y: 204,
    width: 68,
    height: 44,
    rotate: 4,
    dishes: [
      {
        name: "Litti Chokha",
        description: "Roasted sattu-filled balls served with smoky mashed vegetables.",
        recipeUrl: "/recipes",
      },
    ],
  },
  {
    id: "gj",
    name: "Gujarat",
    x: 56,
    y: 286,
    width: 92,
    height: 84,
    rotate: -8,
    dishes: [
      {
        name: "Undhiyu",
        description: "A winter vegetable medley cooked slowly with herbs and fenugreek dumplings.",
        recipeUrl: "/recipes",
      },
      {
        name: "Khandvi",
        description: "Silky gram flour rolls finished with coconut and a mustard seed tempering.",
        recipeUrl: "/recipes",
      },
    ],
  },
  {
    id: "mp",
    name: "Madhya Pradesh",
    x: 166,
    y: 274,
    width: 106,
    height: 76,
    rotate: -2,
    dishes: [
      {
        name: "Bhutte ka Kees",
        description: "Indore's creamy grated corn dish brightened with milk and green chili.",
        recipeUrl: "/recipes",
      },
    ],
  },
  {
    id: "ct",
    name: "Chhattisgarh",
    x: 286,
    y: 286,
    width: 66,
    height: 72,
    rotate: 3,
    dishes: [
      {
        name: "Chila",
        description: "Savory rice-lentil pancakes loved across Chhattisgarhi kitchens.",
        recipeUrl: "/recipes",
      },
    ],
  },
  {
    id: "jh",
    name: "Jharkhand",
    x: 354,
    y: 258,
    width: 58,
    height: 54,
    rotate: 4,
    dishes: [
      {
        name: "Dhuska",
        description: "Deep-fried rice-lentil bread often served with spicy potato curry.",
        recipeUrl: "/recipes",
      },
    ],
  },
  {
    id: "wb",
    name: "West Bengal",
    x: 408,
    y: 230,
    width: 50,
    height: 108,
    rotate: 10,
    dishes: [
      {
        name: "Shorshe Ilish",
        description: "Hilsa steamed in a bold mustard paste that defines Bengali flavor.",
        recipeUrl: "/recipes",
      },
      {
        name: "Mishti Doi",
        description: "A caramel-toned sweet yogurt with a set, creamy finish.",
        recipeUrl: "/recipes",
      },
    ],
  },
  {
    id: "sk",
    name: "Sikkim",
    x: 456,
    y: 204,
    width: 28,
    height: 28,
    rotate: 0,
    dishes: [
      {
        name: "Phagshapa",
        description: "A comforting stew of radish and chilies rooted in the Himalayan table.",
        recipeUrl: "/recipes",
      },
    ],
  },
  {
    id: "as",
    name: "Assam",
    x: 482,
    y: 220,
    width: 72,
    height: 34,
    rotate: 6,
    dishes: [
      {
        name: "Masor Tenga",
        description: "A bright fish curry balanced by tomatoes, lemon, or elephant apple.",
        recipeUrl: "/recipes",
      },
    ],
  },
  {
    id: "or",
    name: "Odisha",
    x: 360,
    y: 330,
    width: 72,
    height: 76,
    rotate: 8,
    dishes: [
      {
        name: "Dalma",
        description: "Temple-style lentils and vegetables perfumed with roasted cumin.",
        recipeUrl: "/recipes",
      },
      {
        name: "Chhena Poda",
        description: "Baked cottage cheese dessert with deeply caramelized edges.",
        recipeUrl: "/recipes",
      },
    ],
  },
  {
    id: "mh",
    name: "Maharashtra",
    x: 142,
    y: 360,
    width: 124,
    height: 92,
    rotate: -4,
    dishes: [
      {
        name: "Misal Pav",
        description: "A fiery moth bean curry topped with farsan and served with bread.",
        recipeUrl: "/recipes",
      },
      {
        name: "Puran Poli",
        description: "Sweet chana dal stuffed flatbread reserved for festive tables.",
        recipeUrl: "/recipes",
      },
    ],
  },
  {
    id: "tg",
    name: "Telangana",
    x: 274,
    y: 398,
    width: 68,
    height: 72,
    rotate: 2,
    dishes: [
      {
        name: "Hyderabadi Biryani",
        description: "Layered dum biryani with saffron, meat, and long-grained rice.",
        recipeUrl: "/recipes",
      },
    ],
  },
  {
    id: "ap",
    name: "Andhra Pradesh",
    x: 336,
    y: 392,
    width: 74,
    height: 124,
    rotate: 8,
    dishes: [
      {
        name: "Gongura Pachadi",
        description: "A tangy roselle leaf chutney with vivid heat and sourness.",
        recipeUrl: "/recipes",
      },
      {
        name: "Pesarattu",
        description: "Green gram crepes often paired with ginger chutney.",
        recipeUrl: "/recipes",
      },
    ],
  },
  {
    id: "ka",
    name: "Karnataka",
    x: 214,
    y: 472,
    width: 88,
    height: 118,
    rotate: -2,
    dishes: [
      {
        name: "Bisi Bele Bath",
        description: "Rice, lentils, and vegetables simmered into a fragrant one-pot meal.",
        recipeUrl: "/recipes",
      },
      {
        name: "Mysore Pak",
        description: "A rich gram flour sweet that melts into ghee-laden crumbs.",
        recipeUrl: "/recipes",
      },
    ],
  },
  {
    id: "tn",
    name: "Tamil Nadu",
    x: 288,
    y: 548,
    width: 78,
    height: 132,
    rotate: 6,
    dishes: [
      {
        name: "Chettinad Chicken",
        description: "Peppery roasted-spice curry with the bold edge of kalpasi and fennel.",
        recipeUrl: "/recipes",
      },
      {
        name: "Pongal",
        description: "A comforting rice-lentil preparation seasoned with pepper and ghee.",
        recipeUrl: "/recipes",
      },
    ],
  },
  {
    id: "kl",
    name: "Kerala",
    x: 224,
    y: 608,
    width: 42,
    height: 108,
    rotate: -10,
    dishes: [
      {
        name: "Appam with Stew",
        description: "Lacy fermented rice hoppers served with a coconut milk vegetable stew.",
        recipeUrl: "/recipes",
      },
      {
        name: "Puttu Kadala",
        description: "Steamed rice flour cylinders paired with black chickpea curry.",
        recipeUrl: "/recipes",
      },
    ],
  },
  {
    id: "ga",
    name: "Goa",
    x: 178,
    y: 514,
    width: 30,
    height: 48,
    rotate: -8,
    dishes: [
      {
        name: "Goan Fish Curry",
        description: "Coconut-rich curry sharpened with kokum and coastal spice.",
        recipeUrl: "/recipes",
      },
      {
        name: "Bebinca",
        description: "Layered Indo-Portuguese dessert baked with coconut milk and egg yolk.",
        recipeUrl: "/recipes",
      },
    ],
  },
  {
    id: "ar",
    name: "Arunachal Pradesh",
    x: 534,
    y: 172,
    width: 46,
    height: 42,
    rotate: 10,
    dishes: [
      {
        name: "Thukpa",
        description: "A soothing noodle soup adapted to the colder mountain climate.",
        recipeUrl: "/recipes",
      },
    ],
  },
  {
    id: "nl",
    name: "Nagaland",
    x: 532,
    y: 236,
    width: 34,
    height: 34,
    rotate: 4,
    dishes: [
      {
        name: "Smoked Pork with Bamboo Shoot",
        description: "Intense, earthy flavors anchored by fermentation and smoke.",
        recipeUrl: "/recipes",
      },
    ],
  },
  {
    id: "mn",
    name: "Manipur",
    x: 552,
    y: 272,
    width: 30,
    height: 30,
    rotate: 4,
    dishes: [
      {
        name: "Eromba",
        description: "Mashed vegetables and fermented fish with bright local chilies.",
        recipeUrl: "/recipes",
      },
    ],
  },
  {
    id: "mz",
    name: "Mizoram",
    x: 542,
    y: 310,
    width: 34,
    height: 38,
    rotate: 2,
    dishes: [
      {
        name: "Bai",
        description: "A gentle vegetable stew that lets herbs and smoked notes lead.",
        recipeUrl: "/recipes",
      },
    ],
  },
  {
    id: "tr",
    name: "Tripura",
    x: 512,
    y: 308,
    width: 26,
    height: 36,
    rotate: 2,
    dishes: [
      {
        name: "Mui Borok",
        description: "Traditional Tripuri fare centered on fermented fish and fresh greens.",
        recipeUrl: "/recipes",
      },
    ],
  },
  {
    id: "ml",
    name: "Meghalaya",
    x: 486,
    y: 266,
    width: 42,
    height: 28,
    rotate: 0,
    dishes: [
      {
        name: "Jadoh",
        description: "A Khasi rice dish cooked with stock and warming aromatics.",
        recipeUrl: "/recipes",
      },
    ],
  },
];
